# TEST API - using Rest Client

# GET the root
GET http://localhost:3000/

###

# GET all contacts
GET http://localhost:3000/contacts

###

# GET one contact by ID (example: Gabriela)
GET http://localhost:3000/contacts/6902cb23305dfb55027e992f

###

# POST create new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Diana",
  "lastName": "Dianderas",
  "email": "Dianita@gmail.com",
  "favoriteColor": "Pink",
  "birthday": "2021-07-06"
}

###

# PUT update contact
PUT http://localhost:3000/contacts/6911176d43580bec90f9a4d7
Content-Type: application/json

{
  "firstName": "Diana",
  "lastName": "Dianderas",
  "email": "Dianita@gmail.com",
  "favoriteColor": "Black",
  "birthday": "2021-07-06"
}

###

# DELETE contact
DELETE http://localhost:3000/contacts/69168c61f599efda0c58d546

###
PUT http://localhost:3000/contacts/6902cba2305dfb55027e9930
Content-Type: application/json

{
  "firstName": "Julian",
  "lastName": "Dianderas",
  "email": "Mateo@gmail.com",
  "favoriteColor": "Black",
  "birthday": "2021-07-06"
}

###

POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Jhon",
  "lastName": "Jones",
  "email": "Dianj@gmail.com",
  "favoriteColor": "Pink",
  "birthday": "2001-07-06"
}